development:
  adapter: postgresql
  encoding: unicode
  database: todo_app_dev
  pool: 5
  username: postgresdev
  password: postgresdev

test:
  adapter: postgresql
  encoding: unicode
  database: todo_app_test
  pool: 5
  username: postgresdev
  password: postgresdev
